### PR TITLE
initial version more mobile friendly version

### PR DESCRIPTION
**Pull request by edewit**
ionic based demo

### CODE REVIEW

**Comment by edewit** [comment]
@corinnekrych want to give it a spin?

**Comment by edewit** [comment]
[RHMAP-2057](https://issues.jboss.org/browse/RHMAP-2057)

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
@edewit as discussed:
+1 for the new design (maybe change navigation bar color from black to red to fit with ios/android style)
some issue with data structure:
- at creation "created" field should appear when lookin in data browser
- at update, no id field should be added to data structure when looking in remote data browser

**Comment by corinnekrych** [comment]
+1
it works nicely now1
ready to merge

**Pull request merged**
